import type { Metadata } from "next";
import "./globals.scss";
import Navbar from "@/components/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="container my-5">
        <main>{children}</main>
        </div>


        {/* <Footer /> */}
      </body>
    </html>
  );
}